version: "2"

services:
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - mongo
      - rabbitmq
    command: rabbitmq:5672

  api:
    image: store.api:local
    links:
      - rabbitmq
      - products-service
    ports:
      - '5000:5000'

  products-service:
    image: store.services.products:local
    links:
      - mongo
      - rabbitmq
    ports:
      - '5010:5010'

  mongo:
    image: mongo
    volumes:
      - './data/db:/data/db'
    ports:
      - '27017:27017'

  rabbitmq:
    image: rabbitmq:3.6.5-management
    ports:
      - '5672:5672'
      - '15672:15672'